# render.yaml
# This file tells Render how to deploy your FastAPI + PostgreSQL app.

services:
  # 1. PostgreSQL Database
  - type: pserv
    name: postgres-db
    env: postgres
    plan: free
    autoDeploy: false

  # 2. FastAPI Web Service
  - type: web
    name: fastapi-db-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /tables

    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString

      - key: CONNECT_API_KEY
        sync: false  # set this manually in Render Dashboard under "Environment"
