services:
  - type: web
    name: fastapi-db-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /tables
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CONNECT_API_KEY
        sync: false
