services:
  # 1) Managed Render Postgres Database
  - type: postgres
    name: postgres-db
    plan: free
    autoDeploy: false

  # 2) FastAPI App (Docker)
  - type: web
    name: fastapi-db-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /tables
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: postgres-db
          property: connectionString
      - key: CONNECT_API_KEY
        sync: false
